version: '3.7'

services:
  app:
    build: .
    volumes:
      - ./project:/app
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app
