version: '3.7'

services:
  app:
    build: .
    volumes:
      - ./project:/app
      - static_volume:/app/src
      - media_volume:/app/media
    env_file:
      - .env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - static_volume:/static
      - media_volume:/media
    restart: always

volumes:
  static_volume:
  media_volume:
