# Generated by Django 5.0.1 on 2024-01-13 05:10

import apps.website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=14)),
                ('purpose', models.CharField(choices=[('1', 'Intrested in joining as a cadet'), ('2', 'Intrested in joining as a staff volunteer'), ('3', 'Intrested in joining as a committee volunteer'), ('4', 'Parent of a current cadet'), ('5', 'Financial support'), ('6', 'Report issue/bug on Website'), ('7', 'Other')], max_length=1)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('0', 'Officer Commanding'), ('1', 'Adjutant'), ('2', 'Training Officer'), ('3', 'SNCO'), ('4', 'Officer'), ('5', 'Instructor'), ('6', 'Padre'), ('7', 'Chairperson'), ('8', 'Treasurer'), ('9', 'Secretary'), ('10', 'Civilian Committee')], max_length=40, null=True)),
                ('rank', models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Mx', 'Mx'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Rev', 'Rev'), ('CI', 'CI'), ('Sgt', 'Sgt'), ('FS', 'FS'), ('WO', 'WO'), ('Plt Off', 'Plt Off'), ('Fg Off', 'Fg Off'), ('Flt Lt', 'Flt Lt'), ('Sqn Ldr', 'Sqn Ldr'), ('Wg Cdr', 'Wg Cdr')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='staff/default.jpg', max_length=255, null=True, upload_to=apps.website.models.get_profile_image_filepath)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
